app = "litevfs-demo"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "iad"

[env]
  PORT = "8080"
  RUST_LOG = "info,litevfs=debug"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = false
  [http_service.concurrency]
    type = "requests"
    soft_limit = 200
    hard_limit = 250
